project:
  title: Ross Bowen
  type: website
  preview:
    port: 4200
    browser: false
    watch-inputs: true

website:
  site-url: https://rossbowen.github.io
  navbar:
    left:
      - text: Home
        href: index.qmd
    right:
      - icon: github
        href: https://github.com/rossbowen
      - icon: rss
        href: index.xml

format:
  html:
    theme:
      light: default
    code-copy: true
    include-in-header:
      - text: |
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
          <link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap" rel="stylesheet" />
    monofont: "Fira Code"

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 